### ISSUE TITLE
Diferença no content-type

### ISSUE THREAD

**Issue by mbertolani** [bittencourtthulio/Horse-Paginate#15]
Solução:

Alterar
LWebResponse.ContentType := 'application/json';
Para
LWebResponse.ContentType := Res.RawWebResponse.ContentType;

**Comment by viniciussanchez** [comment]
Qual o problema da forma que estava?

**Comment by mbertolani** [comment]
se eu alterar o padrao no jhonson (ex: iso-8859-1) o paginate vai continuar usando UTF-8 dando problema na acentuação quando o json esta paginado.
