### ISSUE TITLE
Como faço pra usar esse recurso com request4delphi

### ISSUE THREAD

**Issue by a86r3** [bittencourtthulio/Horse-Paginate#18]
Boa tarde, como faço pra usar esse recurso usando .dataset(tabmem) ?

**Comment by viniciussanchez** [comment]
Não entendi muito bem o problema...
Poderia exemplificar mais ou menos o que quer? Mostrar código de como está fazendo?

**Comment by a86r3** [comment]
Então estou usando o RESTRequest4D. Sempre uso a recurso para salvar em tabela de memoria sem a paginação ele carrega de boa, mais quando ativo como abaixo ele não salva por conta acho eu do parse (docs) que vem quando habilita o paginate.


Segue abaixo como estou fazendo
var
   LResponse: IResponse;
  jsonObj, jSubObj: TJSONObject;
  ja: TJSONArray;
  jv: TJSONValue;
  i: Integer;
begin
   LResponse := TRequest.New.BaseURL('http://localhost:9001/msg')
    .TokenBearer(toten)
    .Accept('application/json')
    .AddHeader('X-Paginate', 'true')
   .DataSetAdapter(FDMemTable1)
    .Get;

**Comment by viniciussanchez** [comment]
Sim, quando você usa o paginate vem um JSON diferente. Você vai ter que fazer o processo diferente tambem

```pascal
LResponse := TRequest.New.BaseURL('http://localhost:9001/msg')
  .TokenBearer(toten)
  .Accept('application/json')
  .AddHeader('X-Paginate', 'true')
  .Get;

FDMemTable1.LoadFromJSON(LResponse.JSONValue.GetValue<string>('docs'), False);
```

Não sei bem se vai funcionar o código acima, fiz de cabeça, mas a ideia é essa

**Comment by a86r3** [comment]
![image](https://user-images.githubusercontent.com/36715285/191331999-d7fabaae-2748-449d-a7dc-180f0dec0941.png)

deu erro, na conversão

**Comment by viniciussanchez** [comment]
```delphi
FDMemTable1.LoadFromJSON(LResponse.JSONValue.GetValue<TJSONArray>('docs'), False);
```

**Comment by a86r3** [comment]
![image](https://user-images.githubusercontent.com/36715285/191336653-b1db0457-ba7b-47a0-bc69-fb194f932f05.png)
Ele esta herdando do dataset.serialize é isso mesmo?

**Comment by viniciussanchez** [comment]
Sim tem que fazer o uses do DataSet.Serialize

**Comment by a86r3** [comment]
![image](https://user-images.githubusercontent.com/36715285/191351298-41c3c4fd-72b4-426a-a294-15ba81f998c3.png)
Ja esta declarada e mesmo erro

**Comment by a86r3** [comment]
OPa, deu certo aqui coloquei o system.json antes do dataset.serialize 
Obrigado!!!
