### ISSUE TITLE
Erro no retorno no Lazarus

### ISSUE THREAD

**Issue by LukeChagastec** [bittencourtthulio/Horse-Paginate#19]
Boa tarde.

Ao utilizar o plugin no Lazarus, um retorno estranho ocorre.
Aplicando as configurações descritas do Paginate, a rotina funciona, porém retorna um "TJsonArray" no lugar do conteúdo, conforme a figura abaixo.

![image](https://github.com/academiadocodigo/Horse-Paginate/assets/89275370/8db28f01-f31c-4eb0-8536-c0b07b247577)

Dentro da codificação do componente, identifiquei que o erro está dentro do fonte "Horse.Paginate", onde há um retorno "ToString", conforme a figura abaixo.

![image](https://github.com/academiadocodigo/Horse-Paginate/assets/89275370/4e8c4c51-0cb4-428c-a329-a0dec3ba2485)

O retorno da rotina, caso seja FPC, deveria ser um "AsJson".

Versão do Lazarus:
- Lazarus 2.2.6 (rev lazarus_2_2_6) 
- FPC 3.2.2 x86_64-win64-win32/win64

Versão do Horse: 3.1.4.

Fico à disposição para esclarecimentos.

**Comment by viniciussanchez** [comment]
@LukeChagastec você tem razão... quer nos enviar um pull request com a correção?

**Comment by LukeChagastec** [comment]
Boa tarde @viniciussanchez, tudo certo?

Criado pull request.

![image](https://github.com/academiadocodigo/Horse-Paginate/assets/89275370/4c0261f5-7fd9-4ef8-87df-0134b4e60676)
