### ISSUE TITLE
Retornar sumario na versão 1.0.4

### ISSUE THREAD

**Issue by sergio-api** [bittencourtthulio/Horse-Paginate#21]
Olá a todos. 
Estava utilizando a versão 1.0.2 em um projeto e usando o retorno da paginação (
"docs",
 "total":,
 "limit": ,
 "page": ,
 "pages": )
Ao criar um novo projeto e adicionar o paginate via boss, vei a versão 1.0.4 e ela não trazia mais essas informações.
Já havia condicionado meus projetos a essa resposta para tratar o recebimento dos dados.
Olhei as atualizações e mesmo incluindo add-summary no header, não retornava.
Tive que alterar o fonte manualmente para trazer essa informação, mas gostaria de saber se há algum tipo de parâmetro que possa enviar pois posso ter deixado passar algo.
Na documentação na capa do projeto ainda esta da forma antiga.
Abraços !

**Comment by viniciussanchez** [comment]
Boa tarde... experimente colocar assim pra ver se vai: THorse.Use(Paginate());
